# This is a basic workflow to help you get started with Actions

name: Staging-Deployment

# Controls when the action will run. 
on:
  push:
    tags:        
      - staging

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - run: npm ci
      - run: npm run build:staging
      - run: ls dist/staging/
      #- run: git branch --set-upstream-to=origin/gh-pages gh-pages

      # - uses: EndBug/add-and-commit@v6.2.0
      #   with:
      #     # remove: dist/staging -r
      #     # Arguments for the git add command
      #     add: dist/staging --force
      #     push: -u origin gh-pages
      #     # The name of the user that will be displayed as the author of the commit
      #     # author_name: GithubAction
      #     # Name of the branch to use, if different from the one that triggered the workflow
      #     branch: gh-pages
      #     # The directory where your repository is located. You should use actions/checkout first to set it up
      #     #cwd: # optional, default is .
      #     # The message for the commit
      #     message: Deploy to staging via github action

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist/staging # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: staging
